### ISSUE TITLE
Error(s) in loading state_dict for MyTransformer:

### ISSUE THREAD

**Issue by YRH0** [ssbuild/llm_finetuning#21]
python infer_finetuning.py
raise error
```python
model_args, data_args  = parser.parse_dict(train_info_args, allow_extra_keys=True)
```
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmptr0d4z0k
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmptr0d4z0k/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/data/yrh/llm_finetuning_tizh/infer_finetuning.py", line 17, in <module>
    model_args, data_args  = parser.parse_dict(train_info_args, allow_extra_keys=True)
    ^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

modification ->
```python
(model_args,)  = parser.parse_dict(train_info_args, allow_extra_keys=True)
```
raise error
Error(s) in loading state_dict for MyTransformer:
	Missing key(s) in state_dict: "transformer_base.transformer.transformer.word_embeddings.weight",

Is it because I didn't do the weight conversion?

**Comment by YRH0** [comment]
> python infer_finetuning.py raise error
> 
> ```python
> model_args, data_args  = parser.parse_dict(train_info_args, allow_extra_keys=True)
> ```
> 
> INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmptr0d4z0k INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmptr0d4z0k/_remote_module_non_scriptable.py Traceback (most recent call last): File "/data/yrh/llm_finetuning_tizh/infer_finetuning.py", line 17, in model_args, data_args = parser.parse_dict(train_info_args, allow_extra_keys=True) ^^^^^^^^^^^^^^^^^^^^^ ValueError: not enough values to unpack (expected 2, got 1)
> 
> modification ->
> 
> ```python
> (model_args,)  = parser.parse_dict(train_info_args, allow_extra_keys=True)
> ```
> 
> raise error Error(s) in loading state_dict for MyTransformer: Missing key(s) in state_dict: "transformer_base.transformer.transformer.word_embeddings.weight",
> 
> Is it because I didn't do the weight conversion?

4.0K    adapter_config.json
4.6M    adapter_model.bin
4.0K    config.json

The size of the model seems to be wrong

**Comment by ssbuild** [comment]
fixed, try.

**Comment by ssbuild** [comment]
what model  ?

**Comment by YRH0** [comment]
> what model ?

bloomz-1b1

**Comment by ssbuild** [comment]
if you finetuing with lora . try infer_lora_finetuning.py .
infer_finetuning if full parameters finetuning.

**Comment by YRH0** [comment]
Thank you. I will try it

**Comment by YRH0** [comment]
> if you finetuning with lora . try infer_lora_finetuning.py . infer_finetuning is full parameters finetuning.

I finish it, it's great
